language: python
python:
  - "2.7"
  - "3.6"
dist: trusty
addons:
  ssh_known_hosts:
  - gnosisdb-kovan.gnosis.pm
services:
  - postgresql
before_script:
  - psql -c 'create database travisci;' -U postgres
before_install:
  - export DJANGO_SETTINGS_MODULE="settings.test" PYTHONPATH="$HOME/build/gnosis/gnosisdb" PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python gnosisdb/manage.py test && coverage run --source=gnosisdb gnosisdb/manage.py test
after_success:
- coveralls
- docker build -t gnosisdb -f docker/web/Dockerfile .
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag gnosisdb gnosispm/gnosisdb:staging
    docker push gnosispm/gnosisdb:staging
  elif [ "$TRAVIS_BRANCH" == "development" ]; then
    docker tag gnosisdb gnosispm/gnosisdb:development
    docker push gnosispm/gnosisdb:development
  elif [ "$TRAVIS_BRANCH" == "feature/DEV-103-autodeploy" ]; then
    docker tag gnosisdb gnosispm/gnosisdb:development
    docker push gnosispm/gnosisdb:development
  fi
