language: python
python:
  - "3.6"
dist: trusty
addons:
  ssh_known_hosts:
  - gnosisdb-kovan.gnosis.pm
services:
  - postgresql
before_script:
  - psql -c 'create database travisci;' -U postgres
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=gnosisdb manage.py test --settings=config.settings.test
after_success:
- coveralls
- # Create Docker image if branch master or develop
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t gnosisdb -f docker/web/Dockerfile .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag gnosisdb gnosispm/gnosisdb:staging;
    docker push gnosispm/gnosisdb:staging;
  elif [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker build -t gnosisdb -f docker/web/Dockerfile .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag gnosisdb gnosispm/gnosisdb:develop;
    docker push gnosispm/gnosisdb:develop;
  fi
